"""Generate the controlled Stage 8 linear-layout master-data subset."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source-materials" / "kitchen-module-reference-comparison.csv"
TARGET = ROOT / "apps-script" / "generated" / "module_size_rules.gs"
VERSION = "module-size-rules-stage3-linear-v1"
EFFECTIVE_FROM = "2026-08-14"
ALLOWED_CLASSES = {
    "base_general",
    "base_drawer",
    "base_sink",
    "base_dishwasher_slot",
    "base_oven",
    "base_hob",
    "base_narrow_cargo",
    "wall_general",
    "wall_dish_dryer",
    "wall_hood",
    "tall_pantry",
    "tall_universal",
    "tall_fridge",
}
ALLOWED_DIMENSIONS = {"width": "WIDTH", "nominal_width": "NOMINAL_WIDTH"}


def load_rows() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    seen: set[tuple[str, int]] = set()
    with SOURCE.open("r", encoding="utf-8-sig", newline="") as handle:
        for source in csv.DictReader(handle):
            if source["record_type"] != "market_baseline":
                continue
            if source["source_layer"] != "PRIMARY":
                continue
            if source["module_class"] not in ALLOWED_CLASSES:
                continue
            if source["dimension"] not in ALLOWED_DIMENSIONS:
                continue
            if source["size_qualifier"] != "exact" or not source["size_value_mm"]:
                continue
            numeric = float(source["size_value_mm"])
            if not numeric.is_integer() or numeric <= 0:
                raise ValueError(f"Invalid layout width in {source['record_id']}")
            width = int(numeric)
            key = (source["module_class"], width)
            if key in seen:
                raise ValueError(f"Ambiguous layout width {key}")
            seen.add(key)
            rank = source["rank"].strip().upper().split("-")[0].split("/")[0]
            if rank not in {"A", "B", "C", "D", "E"}:
                raise ValueError(f"Invalid rank in {source['record_id']}")
            provenance = [
                f"source-materials/kitchen-module-reference-comparison.csv#{source['record_id']}",
                source["source_ref"],
            ]
            rows.append(
                {
                    "module_rule_id": source["record_id"],
                    "module_class": source["module_class"],
                    "module_role": "",
                    "dimension": ALLOWED_DIMENSIONS[source["dimension"]],
                    "size_value_mm": width,
                    "size_min_mm": "",
                    "size_max_mm": "",
                    "size_qualifier": "EXACT",
                    "rank": rank,
                    "rule_status": "CONFIRMED",
                    "source_layer": "PRIMARY",
                    "source_record_id": source["record_id"],
                    "lifecycle_status": "ACTIVE",
                    "effective_from": EFFECTIVE_FROM,
                    "effective_to": "",
                    "provenance": json.dumps(provenance, ensure_ascii=False),
                    "display_name": f"{source['module_class']} {width} mm",
                    "notes": source["recommended_use"],
                }
            )
    if not rows:
        raise ValueError("No Stage 8 module-size rules were generated")
    return sorted(rows, key=lambda row: (str(row["module_class"]), int(row["size_value_mm"])))


def render() -> str:
    payload = json.dumps(load_rows(), ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "/** Generated by tools/generate_module_size_rules.py; do not edit. */\n"
        f"var STAGE8_MODULE_SIZE_RULES_VERSION = {json.dumps(VERSION)};\n"
        f"var STAGE8_MODULE_SIZE_RULES = {payload};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            raise SystemExit("generated module-size rules are stale")
        print("generated module-size rules are current")
        return
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
